name: Android Build
on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      
      - name: Step 1 - Checkout main branch from GitHub
        uses: actions/checkout@v2

      - name: Step 2 - Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
        
      - name: Step 3 - Assemble Debug
        run: ./gradlew assembleDebug
        
      - name: Step 4 - Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: app/build/outputs/apk/debug/**.apk
