name: Android Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  test:
    runs-on: macos-latest
    steps:
    - name: Step 1 - Checkout main branch from GitHub
      uses: actions/checkout@v2

    - name: Step 2 - Restore Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Step 3 - Run UI Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 28
        target: default
        arch: x86_64
        profile: Nexus 6
        script: ./gradlew connectedCheck --continue

    - name: Step 4 - Upload Test Reports
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: test-reports
        path: '**/build/reports/tests/'